// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NationalParksApi.Models;

namespace NationalParksApi.Migrations
{
    [DbContext(typeof(NationalParksApiContext))]
    partial class NationalParksApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NationalParksApi.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Description = "A beautiful little park.",
                            Location = "Wyoming",
                            Name = "Yellow Stone"
                        },
                        new
                        {
                            ParkId = 2,
                            Description = "Big 'Ol Deep Clear Lake",
                            Location = "Oregon",
                            Name = "Crater Lake"
                        },
                        new
                        {
                            ParkId = 3,
                            Description = "Big 'Ol Mountain",
                            Location = "California",
                            Name = "Big Bear"
                        },
                        new
                        {
                            ParkId = 4,
                            Description = "Big 'Ol crack in the ground",
                            Location = "Nevada",
                            Name = "Grand Canyon"
                        },
                        new
                        {
                            ParkId = 5,
                            Description = "Big Ol Trees",
                            Location = "California",
                            Name = "Jedidiah Smith RedWoods"
                        },
                        new
                        {
                            ParkId = 6,
                            Description = "Dirty Ol Water",
                            Location = "Florida",
                            Name = "EverGlades"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
